---
title: "Schedule"
pagetitle: "Schedule BSTA 526"
date: "1/05/26"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
    # toc: true
editor_options: 
  chunk_output_type: console
---

-   *Schedule is subject to change.*
-   Links have been added to all weeks, but weeks we have not covered yet will have broken links.

```{r setup, include=FALSE}
source(here::here("schedule_class_dates.R"))
```


| Week | Date | Topics |
|:---:|:--:|:---|
| [1](weeks/week_01.qmd) | Th `r format(w1d1, "%m/%d")` | Introduction to course/expectations, Intro to R/RStudio, Functions, Vectors, Data Types |
|  |  |  |  |
| [2](weeks/week_02.qmd) | Th `r format(w2d1, "%m/%d")` | Loading Data, data.frames, and ggplot2 |
|  | | HW 1 due |
|  |  |  |  |
|[3](weeks/week_03.qmd) | Th `r format(w3d1, "%m/%d")` | dplyr: subsetting using filter()/select(), more ggplot: themes, scales, facets |
|  | | HW 2 due |
|  |  |  |  |
|[4](weeks/week_04.qmd) | Th `r format(w4d1, "%m/%d")` | dplyr: mutate(), across(), case_when(), factors, summarize() and group_by(); ggplot: boxplots, scales |
|  | | HW 3 due |
|  |  |  |  |
| 5 | Th `r format(w5d1, "%m/%d")` |  data wrangling practice: forcats, stringr, separate(); combining multiple tables (left_join() etc); reshaping data (i.e. pivot_longer()) |
|  | | HW 4 due |
|  |Th `r format(midterm_open, "%m/%d")` | **[Take Home Midterm Assigned]{style="color:#046b94;"}** |  |
|  |  |  |  |
| 6 | Th `r format(w6d1, "%m/%d")` | More data wrangling practice |
|  | | HW 5 due |
|  |  |  |  |
| 7 | Th `r format(w7d1, "%m/%d")` | More data wrangling practice ctd.  |
|  | | HW 6 due |
|  | Su `r format(midterm_due, "%m/%d")` | **[Take home Midterm due (Sunday)]{style="color:#046b94;"}** |  |
|  |  |  |  |
| 8 | Th `r format(w8d1, "%m/%d")` | Intro to functions, working with lists |
|  | | HW 7 due |
|  |  |  |  |
| 9 | Th `r format(w9d1, "%m/%d")` | Iteration |
|  | | HW 8 due |
|  |  |  |  |
| 10 | Tu `r format(final_open, "%m/%d")` | **[Final Exam Assigned (Tuesday)]{style="color:#046b94;"}** |  |
|  | Th `r format(w10d1, "%m/%d")` | More Stats/Purrr |
|  | | HW 9 due |
|  |  |  |  |
| 11 | Th `r format(w11d1, "%m/%d")` | No Class, Office Hour |  |
|  | | HW 10 due |
|  | Fri `r format(final_due, "%m/%d")` | **[Final Exam Due (Friday 5pm end of term)]{style="color:#046b94;"}** |  |
: {.hover .rowlines tbl-colwidths="\[8, 8, 40\]"}
